const {test,expect}=require('@playwright/test');
test('desk opens first; optional phrase capture and replay retain normal instrument controls',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.locator('#show-desk')).toBeVisible();
  await expect(page.locator('#room-panel')).toBeVisible();
  await expect(page.locator('#show-run')).toBeDisabled();
  await page.locator('#btn-host').click();
  await page.waitForFunction(()=>Clock.ready&&me()?.instrumentReady);
  for(const id of ['gestures','roles','calibration']) await expect(page.locator('#enable-'+id)).not.toBeChecked();
  await page.locator('#room-panel .panel-heading button').click();
  await page.locator('#place-circle').click();await page.locator('#instrument-toggle').click();
  await page.locator('#enable-gestures').check();
  await page.waitForFunction(()=>App.room.show.gesturesEnabled);
  await page.locator('#instrument-lead').fill('800');
  await page.locator('#gesture-record').click();
  await page.getByRole('button',{name:'Play D3 (A)',exact:true}).click();
  await page.waitForFunction(()=>Extras.notes.length===1&&Instrument.played>0);
  await page.locator('#gesture-record').click();
  expect(await page.evaluate(()=>Extras.duration)).toBeGreaterThanOrEqual(250);
  const before=await page.evaluate(()=>Instrument.played);
  await page.locator('#gesture-replay').click();
  await page.waitForFunction(n=>Instrument.played>n,before);
  await page.locator('#enable-gestures').uncheck();
  await page.waitForFunction(()=>!App.room.show.gesturesEnabled&&!Extras.replaying&&!Extras.recording);
  await expect(page.locator('#gesture-controls')).toBeHidden();
  await page.locator('#invite-phones').click();await expect(page.locator('#qr svg')).toBeVisible();
  await page.screenshot({path:'test-results/desk-optional.png',fullPage:true});
  expect(errors).toEqual([]);
});
test('enabling microphone option requests no permission; denial leaves audio and trims intact',async({page,browser})=>{
  await page.goto('/');await page.locator('#btn-host').click();
  await page.waitForFunction(()=>Clock.ready&&me()?.instrumentReady);
  const code=await page.locator('#room-code').innerText();
  const context=await browser.newContext();const phone=await context.newPage();
  await phone.goto('/#'+code);await phone.locator('#btn-join').click();
  await page.waitForFunction(()=>App.room.devices.length===2&&App.room.devices.every(d=>d.instrumentReady));
  await page.locator('#room-panel .panel-heading button').click();
  await page.locator('#place-circle').click();
  await page.evaluate(()=>{window.micAttempts=0;Acoustic.open=async()=>{window.micAttempts++;throw new Error('Microphone permission denied');};});
  await page.locator('#enable-calibration').check();await page.waitForFunction(()=>App.room.show.calibrationEnabled);
  expect(await page.evaluate(()=>window.micAttempts)).toBe(0);
  await page.locator('#timing-measure').click();await expect(page.locator('#timing-status')).toContainText('permission denied');
  expect(await page.evaluate(()=>({attempts:window.micAttempts,stream:Acoustic.stream,trim:App.trim,running:Timing.running}))).toEqual({attempts:1,stream:null,trim:0,running:false});
  await page.locator('#enable-calibration').uncheck();await page.waitForFunction(()=>!App.room.show.calibrationEnabled);
  await page.locator('#enable-roles').check();await page.waitForFunction(()=>App.room.show.rolesEnabled);
  for(const checkbox of await page.locator('#role-devices input').all()) await checkbox.check();
  await page.locator('#role-bulk').selectOption('visual');await page.locator('#role-assign').click();
  await page.waitForFunction(()=>App.room.devices.every(d=>d.role==='visual'));
  await page.locator('#enable-roles').uncheck();await page.waitForFunction(()=>!App.room.show.rolesEnabled);
  await context.close();
});
