const { test, expect } = require('@playwright/test');
test('polyrhythm drives scheduled phone visuals, diagnostics and blackout', async ({ page, browser }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/'); await page.locator('#btn-host').click();
  await page.waitForFunction(() => Clock.ready && me()?.instrumentReady);
  const code = await page.locator('#room-code').innerText();
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const phone = await context.newPage(); phone.on('pageerror', e => errors.push(e.message));
  await phone.goto('/#' + code); await phone.locator('#btn-join').click();
  await phone.waitForFunction(() => Clock.ready && me()?.instrumentReady);
  await page.waitForFunction(() => App.room.devices.length === 2 && App.room.devices.every(d => d.visualReady && d.instrumentReady));
  await page.locator('#place-circle').click();
  await phone.locator('#enter-stage').click(); await expect(phone.locator('#phone-stage')).toBeVisible();
  await page.locator('#show-run').click();
  await phone.waitForFunction(() => Instrument.played >= 3 && Stage.visualCount >= 3);
  await page.waitForFunction(() => App.room.devices.every(d => d.metrics?.played > 0));
  expect(await page.locator('#phone-wall canvas').count()).toBe(2);
  expect(await phone.evaluate(() => { const c = document.querySelector('#stage-canvas'); return c.width > 0 && Stage.activity.size > 0; })).toBe(true);
  await page.locator('#show-blackout').click();
  await phone.waitForFunction(() => Stage.show().blackout);
  expect(await phone.evaluate(() => Stage.level(Stage.activity.get(App.id), Clock.now(), Stage.show()))).toBe(0);
  await page.locator('#show-stop').click();
  await phone.waitForFunction(() => !Stage.show().running && Instrument.voices.size === 0 && Stage.queue.length === 0);
  const download = page.waitForEvent('download'); await page.locator('#download-diagnostics').click();
  expect((await download).suggestedFilename()).toContain('diagnostics.json');
  await phone.locator('#exit-stage').click(); await expect(phone.locator('#phone-stage')).toBeHidden();
  await page.screenshot({ path: 'test-results/show-desktop.png', fullPage: true });
  expect(errors).toEqual([]); await context.close();
});
